export {
  CONTRACT_ERRORS,
  CONTRACT_ERRORS_BY_CONTRACT,
  type ContractErrorCode,
  type ContractErrorInfo,
  type ContractErrorName,
  type ContractName,
  getErrorsForContract,
  getContractError,
  isValidErrorCode,
  isValidContractErrorCode,
} from "./generated/contract-errors";

export const LENDING_CONTRACT_ID =
  "CDTWMEFOCTZOYCOJMTFCDLKKZIDDH5ZUGVYWSIB3R3QCFFQO3VPO6O6Z";

export const LENDING_POOL2_CONTRACT_ID =
  "CDZWW5XCWA6J3AHZJLN7VU5I5QMMZFUPYKIF3M6IOOWU23C25PXVRI37";

export const ORACLE_CONTRACT_ID =
  "CCFWASXOQJVJR5WVHRQPQTLCZC3SCBAL2Z67YY4JJAO5GLJLJABQT47I";

export const BACKSTOP_CONTRACT_ID =
  "CDTFRINWJOMLGYS64N7JICGNBCFKKSPJBNMI7FHTDOHZQ2RAKTJEXCRO";

export const BACKSTOP_POOL2_CONTRACT_ID =
  "CARYWBLZCXSSZSSGL2VRVDS57P7KIV7NOBESGBR3SKQXDIFDDZRRFHQ6";
